### ISSUE TITLE
python3 store_block_data.py -->null &

### ISSUE THREAD

**Issue by tommaay** [trinity-project/trinity#21]
I'm stuck on step 11. I am getting an error after entering the command "python3 store_block_data.py -->null &"

The error says: "ImportError: No module named 'pymysql'

<img width="730" alt="screen shot 2018-03-12 at 11 44 17 pm" src="https://user-images.githubusercontent.com/26946743/37326462-82bd0e3e-264f-11e8-8353-af33e774f9d6.png">

**Comment by xiaohuta** [comment]
hi, 


There are some mandotory python plugin is not installed. you could try to run the shell scripts "source ./prepare_env.sh" under trinity-master on your vm.


then try it again.


thanks :-)



At 2018-03-13 14:46:05, "Tommy Huynh" <notifications@github.com> wrote:


I'm stuck on step 11. I am getting an error after entering the command "python3 store_block_data.py -->null &"

The error says: "ImportError: No module named 'pymysql'

**Comment by tommaay** [comment]
Hmm I tried it and it still didn't work for me. Thanks for helping though!

**Comment by xiaohuta** [comment]
could you please follow the below steps to trace what happened on your env:
1. check the environment PYTHONPATH: echo $PYTHONPATH, if not set, please set this value as $(yourdir)/trinity-master/src
2. run python3 in your terminal, then input "import pymysql", if failed, please install the python packages manually by pip3 install.
3. run your command and check what will happen.

Appreciated for your interests on Trinity.

**Comment by tommaay** [comment]
![screen shot 2018-03-14 at 8 00 15 pm](https://user-images.githubusercontent.com/26946743/37442245-5eeea39a-27c2-11e8-8c11-dadbd685bcd1.png)

Do I need to upgrade the version?

**Comment by xiaohuta** [comment]
Maybe already in your vm， please find pip3. if could not find that, you could update your pip and try it later. 

if error still occurs, please use apt-get install python3-pip to try again.

Thank you for your great job.
